spring:
  application:
    name: bank_rest
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/migration/db-changelog-master.yaml
    enabled: true
    url: jdbc:postgresql://postgres:5432/bankdb
    default-schema: public
    liquibase-schema: public
    user: postgres
    password: postgres

jwt_secret: string123
jwt_expiration_period: 900000
logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
